 /******************************************************************************
 *
 * Module: LCD
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the Ultrasonic driver
 *
 * Author: Ahmed Magdy
 *we will adjust the pins here to match the required in the  project
 *******************************************************************************/
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_
#include "gpio.h"
#include "std_types.h"
# include "icu.h"
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
//define trigger and echo(ICU) pins
# define Ultrasonic_Trigger_Port 			PORTB_ID
# define Ultrasonic_Trigger_Pin 			PIN5_ID

# define Ultrasonic_Echo_Port 				PORTD_ID
# define Ultrasonic_Echo_Pin 				PIN6_ID
# define Ultrasonic_Trigger_Pulse_duration 	10 //delay value after we send trigger pulse
# define Ultrasonic_Distance_Constant 		0.017
/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * Description:
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
 void Ultrasonic_init(void);
/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */
 void Ultrasonic_Trigger(void);
/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 * Output:The measured distance in Centimeter.
 */

 uint16 Ultrasonic_readDistance(void);
/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
 void Ultrasonic_edgeProcessing(void);

#endif
